Enhance linting tasks in Taskfile.yml for improved error handling
- Updated markdownlint command to use quotes for better path handling.
- Added conditional check for the existence of _config.yml before running yamllint, with a warning message if the file is not found. This improves robustness in the linting process.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -45,8 +45,14 @@ tasks:
     desc: Lint markdown files and front matter
     deps: [lint:pull]
     cmds:
-      - docker run -v ${PWD}:/workdir --rm -w /workdir davidanson/markdownlint-cli2 "_posts/**/*.md" "*.md"
-      - docker run -v ${PWD}:/workdir --rm -w /workdir cytopia/yamllint _config.yml _posts/
+      - docker run -v "${PWD}:/workdir" --rm -w /workdir davidanson/markdownlint-cli2 "_posts/**/*.md" "*.md"
+      - |
+        if [ -f "_config.yml" ]; then
+          docker run -v "${PWD}:/workdir" --rm -w /workdir cytopia/yamllint .
+        else
+          echo "Warning: _config.yml not found"
+          exit 1
+        fi
 
   lint:pull:
     desc: Pull required Docker images
